[tox]
envlist = py310,coverage
skipsdist = true

[testenv]
description = Run tests for {envname}
package = editable
extras = test
setenv =
    PYTHONPATH = {toxinidir}/src
    ASKMETC_TEST_STUBS = 1
    ASKMETC_TEST_DEBUG = 0
deps =
    coverage==7.5.1
    tox==4.15.1
commands =
    python -m pytest --cov=asketmc_bot --cov-report=term-missing --cov-report= --cov-append --cov-context=test

[testenv:coverage]
description = Combine and report coverage from all envs
deps =
    coverage==7.5.1
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    python -m coverage combine
    python -m coverage report -m
    python -m coverage xml -o coverage.xml
    python -m coverage html -d htmlcov
